<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RolesAndPermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear cache and reset permissions before seeding
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        $role = Role::firstOrCreate(['name' => 'admin']);
        $role2 = Role::firstOrCreate(['name' => 'store representative']);
        $role3 = Role::firstOrCreate(['name' => 'request approver']);

        $permissions = [
            "add stock quantity",
            "approve interco requests",
            "approve mass order",
            "approve month end count level 1",
            "approve month end count level 2",
            "approve wastage level 1",
            "approve wastage level 2",
            "cancel wastage approval level 1",
            "cancel wastage approval level 2",
            "commit interco requests",
            "commit store orders",
            "create bom",
            "create branch",
            "create cs mass commits",
            "create dts mass orders",
            "create interco requests",
            "create knowledge base articles",
            "create mass orders",
            "create month end count templates",
            "create month end schedules",
            "create new items",
            "create orders cutoff",
            "create POSMasterfile",
            "create POSMasterfile BOM",
            "create roles",
            "create sapitems",
            "create soh adjustment",
            "create store transactions",
            "create supplier",
            "create SupplierItems",
            "create templates",
            "create users",
            "create wastage record",
            "delete bom",
            "delete branch",
            "delete items",
            "delete knowledge base articles",
            "delete month end count templates",
            "delete month end schedules",
            "delete POSMasterfile",
            "delete POSMasterfile BOM",
            "delete roles",
            "delete sapitems",
            "delete soh adjustment",
            "delete supplier",
            "delete SupplierItems",
            "delete templates",
            "delete users",
            "delete wastage approval level 1",
            "delete wastage approval level 2",
            "delete wastage record",
            "download month end count template",
            "edit bom",
            "edit branch",
            "edit cs dts mass commit",
            "edit cs mass commits",
            "edit dsp delivery schedules",
            "edit dts delivery schedules",
            "edit dts mass orders",
            "edit finished good commits",
            "edit interco requests",
            "edit items",
            "edit knowledge base articles",
            "edit mass orders",
            "edit month end count approval items",
            "edit month end count items",
            "edit month end count templates",
            "edit month end schedules",
            "edit ordering template approval",
            "edit orders cutoff",
            "edit other commits",
            "edit POSMasterfile",
            "edit POSMasterfile BOM",
            "edit roles",
            "edit sapitems",
            "edit soh adjustment",
            "edit store transactions",
            "edit supplier",
            "edit SupplierItems",
            "edit templates",
            "edit users",
            "edit wastage approval level 1",
            "edit wastage approval level 2",
            "edit wastage record",
            "export actual cost cogs report",
            "export approved orders",
            "export bom list",
            "export branches",
            "export consolidated so report",
            "export cs mass commits",
            "export delivery report",
            "export dts delivery schedules",
            "export dts mass orders",
            "export interco receiving",
            "export interco report",
            "export interco requests",
            "export inventory movement report",
            "export items list",
            "export month end count templates",
            "export ordering calendar",
            "export pmix report",
            "export POSMasterfile BOM",
            "export POSMasterfile list",
            "export qty variance cost variance report",
            "export sapitems list",
            "export soh adjustment",
            "export stock management",
            "export stock management history",
            "export store commits",
            "export store transactions",
            "export SupplierItems list",
            "export suppliers",
            "export templates",
            "export wastage record",
            "export wastage report",
            "import month end count templates",
            "import POSMasterfile BOM",
            "log stock usage",
            "manage references",
            "perform month end count",
            "receive interco requests",
            "receive orders",
            "reject mass order",
            "show mass orders",
            "show orders cutoff",
            "show roles",
            "upload month end count transaction",
            "view actual cost cogs report",
            "view approved order",
            "view approved orders",
            "view bom",
            "view bom list",
            "view branches",
            "view consolidated so report",
            "view cost mass orders",
            "view cost wastage record",
            "view cs dts mass commit",
            "view cs mass commits",
            "view delivery report",
            "view dsp delivery schedule",
            "view dsp delivery schedules",
            "view dts delivery schedules",
            "view dts mass orders",
            "view import logs",
            "view interco approvals",
            "view interco receiving",
            "view interco receiving approvals",
            "view interco report",
            "view interco requests",
            "view inventory movement report",
            "view item",
            "view knowledge base articles",
            "view mass order approval",
            "view mass orders",
            "view month end count approvals",
            "view month end count approvals level 2",
            "view month end count templates",
            "view month end count transaction",
            "view month end schedules",
            "view order calculator",
            "view ordering calendar",
            "view ordering template approval",
            "view orders cutoff",
            "view pmix report",
            "view POSMasterfile BOM",
            "view POSMasterfile BOM list",
            "view POSMasterfile list",
            "view qty variance cost variance report",
            "view roles",
            "view sales budget uploader",
            "view sapitems list",
            "view soh adjustment",
            "view stock management",
            "view stock management history",
            "view store commits",
            "view store transaction",
            "view store transactions",
            "view SupplierItems list",
            "view suppliers",
            "view templates",
            "view total cost in wastage approval level 1",
            "view total cost in wastage approval level 2",
            "view user",
            "view users",
            "view wastage approval level 1",
            "view wastage approval level 2",
            "view wastage record",
            "view wastage report",
        ];

        foreach ($permissions as $permission) {
            Permission::firstOrCreate(['name' => $permission]);
        }

        // Roles for category-specific editing in CS Mass Commits
        $editFinishedGood = Permission::where('name', 'edit finished good commits')->first();
        $editOther = Permission::where('name', 'edit other commits')->first();

        $finishedGoodEditorRole = Role::firstOrCreate(['name' => 'Finished Goods CS']);
        if ($editFinishedGood) {
            $finishedGoodEditorRole->syncPermissions([$editFinishedGood]);
        }

        $generalEditorRole = Role::firstOrCreate(['name' => 'General CS']);
        if ($editOther) {
            $generalEditorRole->syncPermissions([$editOther]);
        }

        // Assign all permissions to the 'admin' role
        $role->syncPermissions(Permission::all());

        // Assign specific permissions to 'store representative'
        $role2->syncPermissions([
            'view dts mass orders', 'create dts mass orders', 'edit dts mass orders',
            'view approved orders', 'view approved order', 'receive orders',
            'view stock management', 'log stock usage', 'add stock quantity', 'view stock management history',
            'export stock management history',
            'view templates', 'view low on stocks',
            'view interco requests', 'create interco requests', 'edit interco requests',
            'view interco receiving', 'receive interco requests',
            'view interco report',
            'view store commits',
            'view items list', 'view sapitems list', 'view SupplierItems list', 'view POSMasterfile list',
            'view bom list', 'view bom', 'create bom', 'edit bom',
            'view soh adjustment', 'create soh adjustment', 'edit soh adjustment',
            'view wastage record', 'create wastage record', 'edit wastage record',
            'view ice cream orders', 'view salmon orders', 'view fruits and vegetables orders',
            'view category list', 'view wip list', 'view menu categories', 'view uom conversions',
            'view inventory categories', 'view unit of measurements', 'view branches', 'view suppliers',
            'view top 10 inventories', 'view days inventory outstanding', 'view days payable outstanding',
            'view sales report', 'view inventories report', 'view upcoming inventories',
            'view account payable', 'view cost of goods',
            'view store transactions', 'create store transactions', 'view store transaction', 'edit store transactions',
            'view POSMasterfile BOM list', 'view POSMasterfile BOM', 'create POSMasterfile BOM', 'edit POSMasterfile BOM', 'import POSMasterfile BOM', 'export POSMasterfile BOM',
            'view consolidated so report',
            'view pmix report',
            'view wastage report',
            'view qty variance cost variance report',
            'view actual cost cogs report',
            'view delivery report',
            'download month end count template',
            'upload month end count transaction',
            'view knowledge base articles',
            'view ordering calendar',
        ]);

        // Assign specific permissions to 'request approver'
        $role3->syncPermissions([
            'view approved received items', 'view received orders for approval list',
            'view approved order for approval',
            'view store transactions approval',
            'view interco requests', 'approve interco requests', 'commit interco requests',
            'view interco approvals',
            'view interco receiving', 'view interco receiving approvals', 'export interco receiving',
            'view interco report', 'export interco report',
            'view store commits', 'commit store orders', 'export store commits',
            'view wastage record',
            'view consolidated so report',
            'view pmix report', 'export pmix report',
            'view wastage report', 'export wastage report',
            'view qty variance cost variance report', 'export qty variance cost variance report',
            'view actual cost cogs report', 'export actual cost cogs report',
            'view delivery report', 'export delivery report',
            'view ordering calendar',
        ]);
    }
}
