@props(['branch', 'orders', 'start_date', 'end_date', 'date_generated', 'generated_by', 'pending', 'commited', 'approved'])
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Store Order Report</title>
    <style>
        body {
            text-align: center;
            margin: 0 auto;
            padding: 20px;
            font-family: Arial, sans-serif;
        }

        p,
        h1,
        h3 {
            margin-left: auto;
            margin-right: auto;
        }

        h1 {
            margin-bottom: 1px;
            font-size: 16px;
            font-weight: bold;
        }

        h3 {
            font-size: 12px;
            margin-top: 5px;
            margin-bottom: 5px;
            font-weight: normal;
        }

        .report-header {
            margin-bottom: 30px;
        }

        .report-info {
            width: 100%;
            margin-top: 20px;
            text-align: left;
            border-top: 1px solid black;
            border-bottom: 1px solid black;
            padding-top: 20px;
            padding-bottom: 20px;
        }

        .info-table {
            width: 100%;
            border-collapse: collapse;
        }

        .info-table td {
            padding: 3px;
            font-size: 12px;
        }

        .left-column {
            width: 50%;
            text-align: left;
        }

        .right-column {
            width: 50%;
            text-align: left;
        }

        .orders-table {
            width: 100%;
            margin-top: 20px;
            border-collapse: collapse;
            text-align: left;
        }

        .orders-table th {
            font-weight: bold;
            font-size: 12px;
            padding: 5px;
            text-align: left;
            margin-bottom: 10px;
        }

        .orders-table td {
            font-weight: normal;
            font-size: 12px;
            padding: 5px;
            text-align: left;
        }

        .table-header {
            border-bottom: 1px solid black;
            margin-bottom: 5px;
        }

        .table-divider {
            border-top: 1px solid black;
            width: 100%;
            margin-top: 5px;
        }
    </style>
</head>

<body>
    <div class="report-header">
        <p>[Company Name]</p>
        <h1>SUMMARY STORE ORDER BY BRANCH</h1>
        <h3>Report Date: [{{ $start_date }}] - [{{ $end_date }}]</h3>
        <h3>(Store Level - Order Quantity)</h3>
    </div>

    <div class="report-info">
        <table class="info-table">
            <tr>
                <td class="left-column">Branch Name: {{ $branch }}</td>
                <td class="right-column">Date Generated: {{ $date_generated }}</td>
            </tr>
            <tr>
                <td class="left-column">Pending Orders: {{ $pending }}</td>
                <td class="right-column">Generated by: {{ $generated_by }}</td>
            </tr>
            <tr>
                <td class="left-column">Approved Orders: {{ $approved }}</td>
                <td class="right-column"></td>
            </tr>
            <tr>
                <td class="left-column">Commited Orders: {{ $commited }}</td>
                <td class="right-column"></td>
            </tr>
        </table>
    </div>

    <table class="orders-table">
        <thead>
            <tr class="table-header">
                <th>Order Date</th>
                <th>Order Placed</th>
                <th>Order Number</th>
                <th>Supplier</th>
                <th>Ordered</th>
                <th>Approved</th>
                <th>Commited</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($orders as $order)
            <tr>
                <td>{{ $order->order_date }}</td>
                <td>{{$order->created_at}}</td>
                <td>{{ $order->order_number }}</td>
                <td>{{ $order->supplier->name }}</td>
                <td>100</td>
                <td>95</td>
                <td>90</td>
                <td>{{ $order->order_status }}</td>
            </tr>
            @endforeach

        </tbody>
    </table>
</body>

</html>