<?php

// Roles and people are resolved from current permissions, never from these labels.
return [
    'order' => ['label' => 'Place a mass order', 'route' => 'mass-orders.index', 'view' => 'view mass orders', 'permissions' => ['create mass orders'], 'rule' => 'Select the branch, ordering template and available delivery date. Submit before the template cutoff. A saved or uploaded order may still require approval.'],
    'dts_order' => ['label' => 'Place a DTS order', 'route' => 'dts-mass-orders.index', 'view' => 'view dts mass orders', 'permissions' => ['create dts mass orders'], 'rule' => 'Use the available dates for the selected template. The ordering window and covered delivery dates depend on its configured cutoff.'],
    'order_approval' => ['label' => 'Review order approval', 'route' => 'mass-orders-approval.index', 'view' => 'view mass order approval', 'permissions' => ['approve mass order'], 'rule' => 'Review requested quantities. Approve to release the order for commitment, or reject with a reason. Only suppliers configured to require approval enter this queue.'],
    'fg_commit' => ['label' => 'Complete finished goods commitments', 'route' => 'cs-mass-commits.index', 'view' => 'view cs mass commits', 'permissions' => ['edit cs mass commits', 'edit finished good commits'], 'rule' => 'Review available quantities, save and confirm commitments. Finished goods and other items have separate editing permissions. The adoption report evaluates applicable commitments against the delivery date.'],
    'other_commit' => ['label' => 'Complete other item commitments', 'route' => 'cs-mass-commits.index', 'view' => 'view cs mass commits', 'permissions' => ['edit cs mass commits', 'edit other commits'], 'rule' => 'Complete and confirm the applicable item commitments. Automated DROPS commitments and categories marked NA do not require a manual adoption task.'],
    'dts_commit' => ['label' => 'Complete DTS commitments', 'route' => 'cs-dts-mass-commits.index', 'view' => 'view cs dts mass commit', 'permissions' => ['edit cs dts mass commit'], 'rule' => 'Review the approved DTS batch and confirm committed quantities before receiving.'],
    'receive' => ['label' => 'Record delivery receiving', 'route' => 'orders-receiving.index', 'view' => 'view approved orders', 'permissions' => ['receive orders'], 'rule' => 'Record actual received quantities and dates, attach the required evidence, and confirm receiving. Partial receipts remain open. If a receipt requires approval, wait for that approval before treating it as complete.'],
    'receipt_approval' => ['label' => 'Review receiving approval', 'route' => 'receiving-approvals.index', 'view' => 'view received orders for approval list', 'permissions' => ['approve received orders'], 'rule' => 'Review pending received quantities and evidence. Approve valid receipts; explain any declined receipt so the receiving user can correct it.'],
    'sales' => ['label' => 'Upload sales', 'route' => 'store-transactions.index', 'view' => 'view store transactions', 'permissions' => ['create store transactions'], 'rule' => 'Upload the sales file for the correct branch and sales date. Read the import results and correct rejected rows. The report measures whether an upload exists separately from whether it met the working-day acceptance rule.'],
    'wastage' => ['label' => 'Record wastage', 'route' => 'wastage.index', 'entry_route' => 'wastage.create', 'view' => 'view wastage record', 'permissions' => ['create wastage record'], 'rule' => 'Create a wastage record with the actual quantities, reasons and required evidence. Submit it for Level 1 review.'],
    'wastage_1' => ['label' => 'Review wastage Level 1', 'route' => 'wastage-approval-lvl1.index', 'view' => 'view wastage approval level 1', 'permissions' => ['approve wastage level 1'], 'rule' => 'Review quantities and available stock. In one-level mode this is final approval; in two-level mode the record goes to Level 2. If stock validation blocks approval, correct the quantity or resolve the stock discrepancy first.'],
    'wastage_2' => ['label' => 'Review wastage Level 2', 'route' => 'wastage-approval-lvl2.index', 'view' => 'view wastage approval level 2', 'permissions' => ['approve wastage level 2'], 'rule' => 'Complete final review of records that reached Level 2. Existing Level 2 records still need completion after a change to one-level mode.'],
    'mec' => ['label' => 'Upload and submit month end count', 'route' => 'month-end-count.index', 'view' => 'perform month end count', 'permissions' => ['perform month end count'], 'rule' => 'Download the branch template, enter the physical count, upload, then review and submit for approval. Uploading alone does not submit the count. The displayed opening date, cutoff and any branch reopening determine when uploads are allowed.'],
    'mec_review' => ['label' => 'Review count and submit for approval', 'route' => 'month-end-count.index', 'view' => 'perform month end count', 'permissions' => ['perform month end count', 'view month end count transaction'], 'rule' => 'The count is uploaded but has not yet been submitted. Review the quantities and submit for Level 1 approval.'],
    'mec_1' => ['label' => 'Review month end count Level 1', 'route' => 'month-end-count-approvals.index', 'view' => 'view month end count approvals', 'permissions' => ['approve month end count level 1'], 'rule' => 'Review the submitted branch quantities and approve Level 1 to hand the count to Level 2.'],
    'mec_2' => ['label' => 'Review month end count Level 2', 'route' => 'month-end-count-approvals-level2.index', 'view' => 'view month end count approvals level 2', 'permissions' => ['approve month end count level 2'], 'rule' => 'Review the Level 1 approved quantities and complete final approval.'],
    'interco' => ['label' => 'Prepare interco request', 'route' => 'interco.index', 'view' => 'view interco requests', 'permissions' => ['create interco requests'], 'rule' => 'Specify the requesting and sending branches and requested quantities. Submit the request for approval.'],
    'interco_approval' => ['label' => 'Review interco request', 'route' => 'interco-approval.index', 'view' => 'view interco approvals', 'permissions' => ['approve interco requests'], 'rule' => 'The requesting branch approval is followed by commitment at the sending branch. Disapproved requests need the reason reviewed before further action.'],
    'interco_commit' => ['label' => 'Commit interco quantities', 'route' => 'store-commits.index', 'view' => 'view store commits', 'permissions' => ['commit store orders'], 'rule' => 'The sending branch reviews available stock and commits the approved quantities. The receiving branch then records the actual receipt.'],
    'interco_receive' => ['label' => 'Receive interco transfer', 'route' => 'interco-receiving.index', 'view' => 'view interco receiving', 'permissions' => ['receive interco requests'], 'rule' => 'The receiving branch records actual quantities and confirms the receipt. An in-transit transfer still has outstanding receiving work.'],
];
